enableImmutableInstalls: false
enableGlobalCache: true
logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard
nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"
pnpMode: loose

# 禁用脚本执行，避免编译问题
enableScripts: false

# 设置网络超时时间（毫秒）
networkTimeout: 100000

# 禁用可选依赖项安装
enableStrictSsl: false
enableNetwork: true

# 构建失败时继续
ignoreScriptErrors: true 